### ISSUE TITLE
configurable dev donation level

### ISSUE THREAD

**Issue by ioojimooi** [fireice-uk/xmr-stak-cpu#113]
when i start the app it says : 
"configurable dev donation level is set to 1.0%"

but i can't find relevant comments in the default config file.

how can this be changed?

**Comment by ibroheem** [comment]
You will have to change the value in the "donate-level.h", then recompile!

**Comment by fireice-uk** [comment]
Correct, while originally I wrote that in with GPL in mind, now it turns out to be quite useful feature with regards to anti-virus compatibility. All but the very dumbest bot herders will recompile the binary instead of taking the one from github, changing the signature, and reducing the problems for the rest of us.
