### ISSUE TITLE
Sorry, unimplemented: 64-bit mode not compiled

### ISSUE THREAD

**Issue by andeees** [fireice-uk/xmr-stak-cpu#12]
First I run:
`cmake -DCMAKE_BUILD_TYPE=STATIC "CodeBlocks - MinGW Makefiles"`

```
And then when I run make:
C:\User\Desktop\xmr-stak-cpu-master>make
Scanning dependencies of target xmr-stak-cpu
[  7%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_blake256.c.obj
C:\Users\User\Desktop\xmr-stak-cpu-master\crypto\c_blake256.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
 /*
 ^
make[2]: *** [CMakeFiles/xmr-stak-cpu.dir/crypto/c_blake256.c.obj] Error 1
make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by dimecoin** [comment]
Does it work if you leave out the static flag?

**Comment by andeees** [comment]
@dimecoin I am using Windows 10, Intel i7 - 4700 (64 bit). I have updated my GCC version to 5.3.0, because I was getting errors with CodeBlocks, and if I build it as 'RELEASE' it still getting error: `C:\Users\Andyy\Desktop\xmr-stak-cpu-master\crypto\c_blake256.c:1:0: sorry, unimplemented: 64-bit mode not compiled in`

**Comment by dimecoin** [comment]
I'm not familiar with CodeBlocks, but is there an option to build as 64bit?

I compiled in VS CE (as 64 bit project) and compiles cleanly.

**Comment by fireice-uk** [comment]
Codeblocks environment is included, but it is configured for Linux builds, since that's where I use it.

From your logs, I can see that you are tying to use it as an IDE for gcc+mingw on Windows - this won't work because mingw is no longer supported and hopelessly outdated, as the error tells you - it just doesn't do 64bits.

If you really don't want to use MSVC then you need to look into using msys2, however a lot of defines in my code assume Microsoft's APIs on Windows and POSIX on other systems. You will most likely get build errors from that, but if you know how to fix them then go for it.

**Comment by rohitpaikra** [comment]
I faced similar problem with codeblocks 17.12 getting an error  message"sorry unimplemented 64-bit mode not compiled".
i resolved it by changing compiler settings.
by following settings->compiler->compiler flags
tick target X86 (32bit) [-m32] int place of target X86_64 (64 bit) [-m64].
![screenshot 8 _li](https://user-images.githubusercontent.com/35983798/35603742-b7a437e0-0664-11e8-9149-ffb1c80b0737.jpg)
