### ISSUE TITLE
win32 Release

### ISSUE THREAD

**Issue by tawrik** [fireice-uk/xmr-stak-cpu#14]
Hi, Is there a 32-bit release?

**Comment by dimecoin** [comment]
What CPU do you have?

I'd almost bet that if your CPU isn't 64-bit, then it most likely doesn't have AES instructions :)

**Comment by fireice-uk** [comment]
I'm starting to get slightly tired from people asking about hardware AES and 64 bits, so let me tell you all a story from early Bitcoin days, back when nobody really saw it really as money, and Jesus walked the earth - (here is how the community felt like)[https://bitcointalk.org/index.php?topic=12.msg54#msg54].

Pretty soon the first private GPU miner came out, and given the same hardware investment, it was around 30x faster. The person that operated it apparently had around 25% of the total hashrate. As you can imagine as soon as the code was public mining on cpus was out of the picture.

Fast forward to XMR. One of the reasons why I felt like dabbling in crypto-money again is that Cryptonight's GPU cost-for-hashrate avantage is only 3-5x. Why?

There are two steps in the function, and both are very fast on modern CPUs
1. AES encryption
2. 64 * 64 bit multiplication with a full 128 bit result

You can do both of those steps in software of course. But what is the point? Your hashrate won't even reach 10H/s and you won't cover even a fraction of the electricity used.

**Comment by tawrik** [comment]
tnx for your full description. but I mean 32-bit operating system not cpu arch.
I was run in 32-bit windows but get this error : `is not valid win32 application.`

**Comment by dimecoin** [comment]
You can do the reverse, run 32-bit applications on a 64-bit OS, but you can't run 64-bit applications on a 32-bit OS.  The requirements are:

* 64-bit CPU
* 64-bit OS
* AES-NI support

Like fireice-uk said, even if you got it to work on win32 it would be really slow.  Some people mine on 32-bit ARM processes (Raspberry PI, for fun), but besides that I doubt you'll get much support for win32 mining scence.  Best bet woudl be to upgrade to a 64-bit OS since you say your CPU is 64-bit.

**Comment by tawrik** [comment]
tnx for your answer, yea I know but Is there a way to compile for win32 in 64-bit CPU ?
I think if compiled for win32 in 64-bit based processor will not effect in performance..
like another miners (minergate,multi miner,etc)

**Comment by fireice-uk** [comment]
No. OS needs to support greater number of address bits than the program, you can fit 32 bits addresses into 64 bit virtual addresses, not the other way round. Since 386 Intel is trying to maintain backwards-compatibility with its processors. I won't bore you with the details, but if you are running a 32bit OS, your CPU is running as a 32bit processor, even if it is more capable.

You can _compile_ 64bit code on a 32bit OS, but you would need to run it on a 64bit OS.

**Comment by dimecoin** [comment]
You are swimming up stream here for very little reward.  There isn't a big demand for this type of setup, so think you will have to forge this trail on your own.  You could try using 64-bit Guest OS (VMWare) on win32 system.  Even if you get it working, I doubt performance will be great.
