### ISSUE TITLE
Antivirus is deleted and detected

### ISSUE THREAD

**Issue by mk148a** [fireice-uk/xmr-stak-cpu#144]
When i opened this miner antivirus is detect and auto delete :( How to fix it? This miner is c ++ code, i know only c#, do you have c# version miner

**Comment by Josexv1** [comment]
Add the miner to the antivirus exclusion list.

**Comment by Elycin** [comment]
A bit more details would help, but also the suggestion above mine.
If you could, to help others: you could contact the virus company and fill out a false-positive form.

**Comment by mk148a** [comment]
i use avira antivir free, its very bad situtation, always close xmr-stak

**Comment by ac0rnsoup** [comment]
I usually create a mining folder that's excluded from antivirus scans. Works like a charm for Windows Defender and Kaspersky. Of course, if you open up an entire folder, be very VERY careful to only download fully trusted miners to that directory from their official sources. There are definitely trojan'd miners out there.

IMHO it's pointless to try any fixes as it will keep getting added to antivirus signatures due to use in botnets. It's a losing battle. Excluding it in your antivirus is the only way.

**Comment by fireice-uk** [comment]
The only possible fix for this issue is to exclude it in your antivirus. I won't write anti-detection code for very obvious reasons.

**Comment by psychocrypt** [comment]
We can't fix wrong results from the AV software, if you not trust the binaries you could compile xmr-stak from source.

**Comment by sheepchen** [comment]
Just for completness: TrentMicro Officescan (and all other TrentMicro products) see the binary as trojan, too.

**Comment by vchrizz** [comment]
Microsoft Defender detects this also as "Win32/Vigorf.A".
I submitted a false-positive form, see: https://www.microsoft.com/en-us/wdsi/submission/a339c4f5-5653-42e1-b705-aaaba528718e

**Comment by andreabisello** [comment]
![image](https://user-images.githubusercontent.com/2149815/51606476-59ebaa80-1f12-11e9-9ae4-fe4306e37c67.png)

i added the folder to the exlusion list.
