### ISSUE TITLE
As of today MS Anti-Virus detects as Skeeyah trojan

### ISSUE THREAD

**Issue by RoscoeT** [fireice-uk/xmr-stak-cpu#217]
My Av updated and deleted the exe.

**Comment by andeees** [comment]
Well same here, you should add it to the exclude list.

**Comment by sgjenks01** [comment]
Window Defender apparently deleted the .exe file AND won't let me download the .zip file that contains the .exe. I don't really know if Defender is reacting to the .zip or the .exe it contains. Regardless, I'm not keen on excluding it because doing so creates an obvious opening for someone to infect the binary. 

Is there a plan to get this fixed so that Windows Defender quits doing this?

**Comment by aaronsace** [comment]
@sgjenks01 Every miner gets blocked by antivirus programs once popular because they get used in botnets. Even if it wasn't blocked, it could be blocked in the middle of you using weeks later. It's open source, just allow it in windows defender. 

You can report the false positive to Microsoft yourself.

**Comment by sgjenks01** [comment]
Okay, got it. Thanks!
