### ISSUE TITLE
-march=native

### ISSUE THREAD

**Issue by renyidong** [fireice-uk/xmr-stak-cpu#28]
Doesn't -march=native usually provides better performance?

**Comment by fireice-uk** [comment]
If you look at my comments 90% of the time is spent inside of the CN loop, and 99% between explode - loop - implode. Every line there is written in SSE2 anyway, so march setting won't make a lot of difference apart from an error on arch below westmere. 

I explored the idea of writing the explode - implode functions in AVX, but since switching between those modes is fairly slow, it negates the gains,

**Comment by jquesnelle** [comment]
I personally use -march=native for my Linux builds but I find that it doesn't really seem to make a difference (like @fireice-uk said 99% of the time is spent in the CN function). One reason to hardcore a processor is that it will compile everywhere and fail at runtime gracefully if the CPU doesn't support AES-NI.  If you use -march=native and compile on a non-AES CPU you get a cryptic compiler error.

**Comment by fireice-uk** [comment]
Actually as of the newest commit it will chug along at some slow speed :). I added software implementations of the CPU instructions, but they are mostly aimed at GPU miners. I just didn't see a reason not to back-port the code and make some people happy.

**Comment by renyidong** [comment]
I recompiled with march=native. Confirmed that's actually slower a bit (a few %). They might be caused by random factors, but apparently not faster, anyway.
