### ISSUE TITLE
What does bfactor means and what does it does?

### ISSUE THREAD

**Issue by GGLW123** [fireice-uk/xmr-stak-cpu#286]
@fireice-uk  Hello, I am unsure how bfactor works, can you explain to me? xD

**Comment by GGLW123** [comment]
and is there a specific calculation which relates it to blocks and threads?

**Comment by brinstarnetworks** [comment]
I think you are looking for xmr-stak-nvidia. However, this is not a support system. It is for reporting bugs in the software.

**Comment by psychocrypt** [comment]
as @brinstarnetworks said it is a xmr-stak-nvidia option and not available for the cpu version.
Thenoption is splitting a long running compute kernel in small kernel to prevent that windows is killing the miner because the gpu not responce during a kernel is blocking the gpu for more than a feew seconds.
