### ISSUE TITLE
xmr-stak-cpu using 200% CPU

### ISSUE THREAD

**Issue by gayanW** [fireice-uk/xmr-stak-cpu#346]
Its my first time mining. I'm doing it just for learning purposes and using my laptop :) I tried enabling and dialing low_power_mode but it didn't make any difference. CPU is constantly at 200%

Output from `top:`
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                           
13661 gayan     20   0  464088   9052   7780 S 200.1  0.2   6:04.27 xmr-stak-cpu 
```
**Specs:**
Debian
[i5-4210U CPU](https://ark.intel.com/products/81016/Intel-Core-i5-4210U-Processor-3M-Cache-up-to-2_70-GHz)

**Config:**
```
"cpu_threads_conf" :
[
    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 2 },
],
```

**Comment by psychocrypt** [comment]
Thats absolutly fine both cores are mining therefore the high load.

Am 22.09.2017 6:23 Nachm. schrieb "Gayan Weerakutti" <
notifications@github.com>:

Its my first time mining. I'm doing it just for learning purposes and using
my laptop :) I tried enabling and dialing low_power_mode but it didn't make
any difference. CPU is constantly at 200%

Output from top:

PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+
COMMAND
13661 gayan     20   0  464088   9052   7780 S 200.1  0.2   6:04.27
xmr-stak-cpu

Specs:
Debian
i5-4210U CPU
<https://ark.intel.com/products/81016/Intel-Core-i5-4210U-Processor-3M-Cache-up-to-2_70-GHz>

Config:

"cpu_threads_conf" :
[
    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 2 },
],

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fireice-uk/xmr-stak-cpu/issues/346>, or mute the thread

**Comment by sunk818** [comment]
@gayanW are you asking for a throttle feature so that CPU is not running 100% each? Maybe 50% CPU?

You can try removing one line so only CPU 0 is high load.

Then you can try [cpulimit](https://unix.stackexchange.com/questions/19203/is-there-a-way-to-limit-overall-cpu-consumption) to reduce the load on CPU 0. For Windows, there is a freeware called BES that works pretty good.
