### ISSUE TITLE
Light

### ISSUE THREAD

**Issue by gustavoghpf** [fireice-uk/xmr-stak-cpu#42]
Hi men, you do not you consider implementing cryptonight lite algorithm to mine aeon?
It has the same price per hash as monero but gives double or more hash than monero per cpu. Its 2x more profitable where I tested. Your miner is great, it would be good to mine aeon too.

**Comment by fireice-uk** [comment]
Hi, you are welcome to fork the miner and change the parameters. It is easy to do, I just don't have the time to maintain Aeon fork

**Comment by shyba** [comment]
@fireice-uk Fork is [here](https://github.com/shyba/aeon-stak-cpu), also generating Windows binaries automatically from AppVeyor. Check it [here](https://ci.appveyor.com/project/shyba/xmr-stak-cpu/branch/master).

Aside from Aeon and AppVeyor changes, my only code change is a compile-time configurable hashes per thread. I will be merging this upstream constantly and try to add a way to configure this miner into Aeon and make a proper PR when I get the time.

Btw, I had to change the donation system to Aeon since the miner would submit invalid shares to your pool. Please provide an Aeon wallet if you want me to send a share of the fork's pool earnings (if it ever gets anything) or provide an Aeon pool so I can change the code back into your pool.

I think you can close this issue now. Feel free to contact me.

I think you can close this issue now.

**Comment by fireice-uk** [comment]
Yes, thanks for doing that BTW, I was about to track down whose miner is pushing Aeon hashes my way =).

I don't have an Aeon wallet (I prefer to keep a fairly tight focus to what I'm working on), feel fee to keep the donations (just don't say they are doing to me), or exchange and send some xmr to my donation wallet:

```
4581HhZkQHgZrZjKeCfCJxZff9E3xCgHGF25zABZz7oR71TnbbgiS7sK9jveE6Dx6uMs2LwszDuvQJgRZQotdpHt1fTdDhk
```
