### ISSUE TITLE
how to start 2 miners

### ISSUE THREAD

**Issue by pbt39ppc** [fireice-uk/xmr-stak-cpu#97]
Hi, i have 8 cores.
i want use 3 for one pool and 3 for another.
did the system let each miner use free cores or i need to change config like that?

------------- pool 1 -------------
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
------------- pool 2 -------------
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },

**Comment by fireice-uk** [comment]
It is much better to affine the threads to a cpu - otherwise the os will swap them around from time to time trashing the cache. Modern OS is designed to favour low-latency response of applications that don't use a lot of cpu power, if that wasn't the case it would ground to a halt a bit like your graphics display when you use a gpu miner.

Your core settings are correct for a Linux OS.
